import argparse
import json
import statistics

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

ALLOCATOR_TO_NAME = {
    "pt": "glibc malloc",
    "je": "jemalloc",
    "mi": "mimalloc",
}

EVENT_TO_NAME = {
    "instructions": "Instructions",
    "cycles": "Cycles",
    "L1-dcache-loads": "L1 Cache Loads",
    "L1-dcache-load-misses": "L1 Cache Misses",
    "LLC-loads": "L3 Cache Loads",
    "LLC-load-misses": "L3 Cache Misses",
    "dTLB-loads": "dTLB Loads",
    "dTLB-load-misses": "dTLB Misses",
}


def main(args: argparse.Namespace) -> None:
    with open(args.file) as f:
        data = json.load(f)

    allocator_data = data[args.allocator]

    occupancies = sorted(allocator_data.keys(), key=float)
    occ_values = [float(o) for o in occupancies]

    baseline_entries = allocator_data[occupancies[0]]
    baseline_time = statistics.mean(e["elapsed"] for e in baseline_entries)

    elapsed_means = []
    elapsed_errs = []
    counter_means = []
    counter_errs = []

    for occ in occupancies:
        entries = allocator_data[occ]
        times = [e["elapsed"] for e in entries]
        counters = [e[args.counter] for e in entries]

        elapsed_means.append(statistics.mean(times) / baseline_time)
        elapsed_errs.append(
            statistics.stdev(times) / baseline_time if len(times) > 1 else 0
        )
        counter_means.append(statistics.mean(counters))
        counter_errs.append(statistics.stdev(counters) if len(counters) > 1 else 0)

    plt.rcParams["pdf.fonttype"] = 42
    plt.rcParams["font.family"] = args.font

    with plt.style.context("bmh"):
        fig, ax_left = plt.subplots()
        fig.set_size_inches(4, 2.5)
        ax_left.set_facecolor("white")

        ax_right = ax_left.twinx()

        color_time = (2 / 255, 81 / 255, 150 / 255)
        color_counter = (253 / 255, 179 / 255, 56 / 255)

        ax_left.errorbar(
            occ_values,
            elapsed_means,
            yerr=elapsed_errs if args.yerr else None,
            color=color_time,
            marker="o",
            markersize=4,
            linewidth=1.5,
            capsize=3,
            label="Normalized Time",
        )

        ax_right.errorbar(
            occ_values,
            counter_means,
            yerr=counter_errs if args.yerr else None,
            color=color_counter,
            marker="s",
            markersize=4,
            linewidth=1.5,
            capsize=3,
            linestyle="--",
            label=EVENT_TO_NAME.get(args.counter, args.counter),
        )

        # Scale right axis so min/max fill the figure
        cmin = min(v - e for v, e in zip(counter_means, counter_errs))
        cmax = max(v + e for v, e in zip(counter_means, counter_errs))
        margin = (cmax - cmin) * 0.05 if cmax != cmin else abs(cmax) * 0.05 or 1
        ax_right.set_ylim(cmin - margin, cmax + margin)

        ax_left.xaxis.grid(False)
        ax_left.yaxis.grid(False)
        ax_right.xaxis.grid(False)
        ax_right.yaxis.grid(False)

        ax_left.set_xlabel("Occupancy")
        ax_left.set_ylabel("Normalized Time")
        ax_right.set_ylabel(EVENT_TO_NAME.get(args.counter, args.counter))

        ax_left.xaxis.set_major_formatter(ticker.PercentFormatter(xmax=1.0))
        ax_right.yaxis.set_major_formatter(
            ticker.FuncFormatter(
                lambda x, _: (
                    f"{x/1e9:.0f}G"
                    if abs(x) >= 1e9
                    else (
                        f"{x/1e6:.0f}M"
                        if abs(x) >= 1e6
                        else (f"{x/1e3:.0f}k" if abs(x) >= 1e3 else f"{x:.0f}")
                    )
                )
            )
        )

        # Combined legend
        lines_left, labels_left = ax_left.get_legend_handles_labels()
        lines_right, labels_right = ax_right.get_legend_handles_labels()
        ax_left.legend(lines_left + lines_right, labels_left + labels_right)

        fig.tight_layout()
        plt.savefig(
            f"plot_cycle.{args.format}", format=args.format, bbox_inches="tight"
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("file", type=str, help="JSON file generated by cycle.py")
    parser.add_argument(
        "--allocator",
        type=str,
        default="pt",
        help="Allocator to plot (e.g. pt, je, mi)",
    )
    parser.add_argument(
        "--counter",
        type=str,
        default="LLC-load-misses",
        help="Perf counter for right axis",
    )
    parser.add_argument("--font", type=str, default="Linux Libertine O")
    parser.add_argument("--format", type=str, default="png")
    parser.add_argument("--yerr", action="store_true", default=False)
    main(parser.parse_args())
